# Esclusione dall'analisi completa (i file non verranno proprio letti)
# In questo caso, i file all'interno di "services/i18n/" e i file JavaScript che corrispondono al pattern "jquery-*.js" non saranno analizzati da SonarQube. Ciò significa che non verranno considerati per il calcolo di metriche, la rilevazione di bug o vulnerabilità, e non contribuiranno alla valutazione complessiva del progetto.
sonar.exclusions=services/i18n/**, JavaScript/jquery-*.js

# Esclusione specifica solo per la Duplicazione (i file vengono analizzati per bug, ma ignorati per il "Copy-Paste")
sonar.cpd.exclusions=services/i18n/**